version: '3.3'

services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    ports:
      - 3050:3050
    stdin_open: true
    environment:
      - PORT=3050
    command: npm start